### ISSUE TITLE
Wrong lookup path

### ISSUE THREAD

**Issue by ybeaufort** [soixantecircuits/standard-settings#4]
At https://github.com/soixantecircuits/standard-settings/blob/master/index.js#L36
`lookUpPath = require.main.filename` should be replaced by `lookUpPath = path.dirname(require.main.filename)` to remove the filename part.

**Comment by gabrielstuff** [comment]
Fixed with https://github.com/soixantecircuits/standard-settings/commit/3825ad96339cb9ce1827c3b20325983136d06d8d
