### ISSUE TITLE
standard-settings only checks if the primary settings path exists

### ISSUE THREAD

**Issue by ybeaufort** [soixantecircuits/standard-settings#5]
At https://github.com/soixantecircuits/standard-settings/blob/master/index.js#L33
the module checks if the primary settings file exists but not the secondary. So, even if the secondary settings file exists, it won't be loaded because there was no checking if it exists.

The if statement should be replaced by something like:
`if (fs.existsSync(path.resolve(process.cwd(), primarySettingsPath)) || fs.existsSync(path.resolve(process.cwd(), secondarySettingsPath)))`

**Comment by gabrielstuff** [comment]
All settings are correctly loaded. Thanks to https://github.com/soixantecircuits/standard-settings/commit/3825ad96339cb9ce1827c3b20325983136d06d8d
